---
- name: Ensure password reuse policy
  hosts: all
  become: yes
  tasks:

    - name: Backup the original common-password file
      copy:
        src: /etc/pam.d/common-password
        dest: /etc/pam.d/common-password.bak
        backup: yes
      tags: backup

    - name: Ensure the remember option is set in the common-password file
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+\[success=1\s+default=ignore\]\s+pam_unix.so'
        line: 'password [success=1 default=ignore] pam_unix.so obscure use_authtok try_first_pass yescrypt remember=5'
        backup: yes
      tags: configure

    - name: Verify the configuration was applied correctly
      command: cat /etc/pam.d/common-password
      register: config_output
      changed_when: false
      tags: verify

    - name: Display the configuration
      debug:
        var: config_output.stdout
      tags: debug

    - name: Ensure the correct hashing algorithm is used in /etc/pam.d/common-password
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+.*\s+pam_unix\.so\s+.*'
        line: 'password [success=1 default=ignore] pam_unix.so obscure use_authtok try_first_pass remember=5'
        backup: yes
      notify: Restart SSH

    - name: Ensure ENCRYPT_METHOD is set to yescrypt in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^ENCRYPT_METHOD'
        line: 'ENCRYPT_METHOD yescrypt'
        backup: yes
    
    - name: Set PASS_MIN_DAYS to 1 in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MIN_DAYS'
        line: 'PASS_MIN_DAYS 1'
        state: present

    - name: Set PASS_MAX_DAYS to 1 in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS 364'
        state: present

    - name: Ensure minimum days between password changes for all users
      shell: |
        for user in $(awk -F: '$2 ~ /^\$/ {print $1}' /etc/shadow); do
          chage --mindays 1 "$user"
        done
      args:
        executable: /bin/bash
      run_once: true

    - name: Ensure max days between password changes for all users
      shell: |
        for user in $(awk -F: '$2 ~ /^\$/ {print $1}' /etc/shadow); do
          chage --maxdays 364 "$user"
        done
      args:
        executable: /bin/bash
      run_once: true

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

    