---
- name: Configure GRUB password on Ubuntu 22.04
  hosts: all
  become: yes

  # vars:
  #   grub_password: "{{ lookup('env', 'GRUB_PASSWORD') }}"
  #   grub_user: "{{ lookup('env', 'GRUB_USERNAME') }}"

  tasks:
    - name: Generate GRUB password hash
      expect:
        command: grub-mkpasswd-pbkdf2
        responses:
          Enter\ password: "{{ grub_password }}"
          Reenter\ password: "{{ grub_password }}"
      register: grub_password_hash
    
    - name: Extract the actual hash from the output
      set_fact:
        actual_grub_password_hash: "{{ grub_password_hash.stdout.split('PBKDF2 hash of your password is ')[1] }}"

    - name: Set GRUB password in 40_custom
      blockinfile:
        path: /etc/grub.d/40_custom
        block: |
          set superusers="{{ grub_username }}"
          password_pbkdf2 {{ grub_username }} {{ actual_grub_password_hash }}
        create: yes

    - name: Ensure permissions on bootloader config are configured
      file:
       path: /boot/grub/grub.cfg
       owner: root
       group: root
       mode: '0400'

    - name: Ensure /etc/default/grub exists
      ansible.builtin.file:
        path: /etc/default/grub
        state: touch

    - name: Update GRUB_CMDLINE_LINUX in /etc/default/grub
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor audit=1"'
        backrefs: yes

    - name: Update GRUB configuration
      ansible.builtin.command:
        cmd: update-grub
        warn: no

    - name: Update GRUB
      command: update-grub
      notify: reboot_server

  handlers:
    - name: reboot_server
      reboot:
