---
- name: Ensure permissions of cron
  hosts: all
  become: yes
  tasks:
    - name: Set ownership of /etc/crontab
      file:
        path: /etc/crontab
        owner: root
        group: root
        state: file

    - name: Set permissions of /etc/crontab
      file:
        path: /etc/crontab
        mode: '0700'

    - name: Set ownership of /etc/cron.hourly
      file:
        path: /etc/cron.hourly
        owner: root
        group: root
        state: directory

    - name: Set permissions of /etc/cron.hourly
      file:
        path: /etc/cron.hourly
        mode: '0700'

    - name: Set ownership of /etc/cron.daily
      file:
        path: /etc/cron.daily
        owner: root
        group: root
        state: directory

    - name: Set permissions of /etc/cron.daily
      file:
        path: /etc/cron.daily
        mode: '0700'

    - name: Set ownership of /etc/cron.weekly
      file:
        path: /etc/cron.weekly
        owner: root
        group: root
        state: directory

    - name: Set permissions of /etc/cron.weekly
      file:
        path: /etc/cron.weekly
        mode: '0700'

    - name: /etc/cron.monthly
      file:
        path: /etc/cron.monthly
        owner: root
        group: root
        state: directory

    - name: Set permissions of /etc/cron.monthly
      file:
        path: /etc/cron.monthly
        mode: '0700'

    - name: Set ownership of /etc/cron.d
      file:
        path: /etc/cron.d
        owner: root
        group: root
        state: directory

    - name: Set permissions of /etc/cron.d
      file:
        path: /etc/cron.d
        mode: '0700'

    - name: Remove /etc/cron.deny if it exists
      file:
        path: /etc/cron.deny
        state: absent

    - name: Create /etc/cron.allow
      file:
        path: /etc/cron.allow
        state: touch
        mode: '0644'
        owner: root
        group: root

    - name: Ensure correct permissions and ownership for /etc/cron.allow
      file:
        path: /etc/cron.allow
        mode: '0644'
        owner: root
        group: root

    - name: Get the list of users in the sudoers group
      command: getent group sudo
      register: sudoers_group

    - name: Add users in sudoers group to /etc/cron.allow
      lineinfile:
        path: /etc/cron.allow
        line: "{{ item }}"
        create: yes
      with_items: "{{ sudoers_group.stdout.split(':')[3].split(',') }}"
      when: sudoers_group.stdout != ""