---
- name: Configure lockout for failed password attempts and password policy
  hosts: all
  become: yes
  tasks:

    - name: Install libpam-pwquality
      apt:
        name: libpam-pwquality
        state: present

    - name: Configure password length in pwquality.conf
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "minlen = 14"
        create: yes
        validate: 'grep -q "^minlen" %s'

    - name: Configure password complexity in pwquality.conf
      block:
        - lineinfile:
            path: /etc/security/pwquality.conf
            line: "minclass = 4"
            create: yes
            validate: 'grep -q "^minclass" %s'

        - lineinfile:
            path: /etc/security/pwquality.conf
            line: "dcredit = -1"
            create: yes
            validate: 'grep -q "^dcredit" %s'

        - lineinfile:
            path: /etc/security/pwquality.conf
            line: "ucredit = -1"
            create: yes
            validate: 'grep -q "^ucredit" %s'

        - lineinfile:
            path: /etc/security/pwquality.conf
            line: "ocredit = -1"
            create: yes
            validate: 'grep -q "^ocredit" %s'

        - lineinfile:
            path: /etc/security/pwquality.conf
            line: "lcredit = -1"
            create: yes
            validate: 'grep -q "^lcredit" %s'

    - name: Ensure pam_faillock is configured in /etc/pam.d/common-auth
      blockinfile:
        path: /etc/pam.d/common-auth
        marker: "# {mark} ANSIBLE MANAGED BLOCK - faillock configuration"
        block: |
          # pam_faillock configuration added by Ansible
          auth required pam_faillock.so preauth
          auth [success=1 default=ignore] pam_unix.so nullok
          auth [default=die] pam_faillock.so authfail
          auth sufficient pam_faillock.so authsucc

    - name: Ensure pam_faillock is configured in /etc/pam.d/common-account
      lineinfile:
        path: /etc/pam.d/common-account
        line: "account required pam_faillock.so"
        insertafter: EOF

    - name: Configure faillock in /etc/security/faillock.conf
      blockinfile:
        path: /etc/security/faillock.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - faillock configuration"
        block: |
          # faillock configuration added by Ansible
          deny = 4
          fail_interval = 900
          unlock_time = 600
